USE warehouse;

CREATE TABLE WAREHOUSE (
  ID varchar(36) NOT NULL,
  WAREHOUSE_KEY varchar(40) NOT NULL,
  CREATEUSERID varchar(40) NOT NULL,
  CREATEPROGID varchar(40) NOT NULL,
  MODIFYUSERID varchar(40) NOT NULL,
  MODIFYPROGID varchar(40) NOT NULL,
  CREATETS datetime DEFAULT current_timestamp(),
  MODIFYTS datetime DEFAULT current_timestamp(),
  DB_LOCK_VERSION bigint(20) DEFAULT 0,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE SHELF_GROUP (
  ID varchar(36) NOT NULL,
  SHELF_GROUP_KEY varchar(40) NOT NULL,
  START_LATITUDE double NOT NULL,
  END_LATITUDE double NOT NULL,
  START_LONGITUDE double NOT NULL,
  END_LONGITUDE double NOT NULL,
  WAREHOUSE_KEY varchar(40) NOT NULL,
  CREATEUSERID varchar(40) NOT NULL,
  CREATEPROGID varchar(40) NOT NULL,
  MODIFYUSERID varchar(40) NOT NULL,
  MODIFYPROGID varchar(40) NOT NULL,
  CREATETS datetime DEFAULT current_timestamp(),
  MODIFYTS datetime DEFAULT current_timestamp(),
  DB_LOCK_VERSION bigint(20) DEFAULT 0,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE SHELF (
  SHELF_KEY varchar(40) NOT NULL,
  SHELF_GROUP_KEY varchar(40) NOT NULL,
  LATITUDE double NOT NULL,
  LONGITUDE double NOT NULL,
  ELEVATION double NOT NULL,
  SHELF_HEIGHT_REMAINING double NOT NULL,
  SHELF_WIDTH_REMAINING double NOT NULL,
  SHELF_LENGTH_REMAINING double NOT NULL,
  ID varchar(36) NOT NULL,
  CREATEUSERID varchar(40) NOT NULL,
  CREATEPROGID varchar(40) NOT NULL,
  MODIFYUSERID varchar(40) NOT NULL,
  MODIFYPROGID varchar(40) NOT NULL,
  CREATETS datetime DEFAULT current_timestamp(),
  MODIFYTS datetime DEFAULT current_timestamp(),
  DB_LOCK_VERSION bigint(20) DEFAULT 0,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE DROP_LOCATION (
  DROP_LOCATION_KEY varchar(40) NOT NULL,
  WAREHOUSE_KEY varchar(40) NOT NULL,
  LATITUDE double NOT NULL,
  LONGITUDE double NOT NULL,
  ID varchar(36) NOT NULL,
  CREATEUSERID varchar(40) NOT NULL,
  CREATEPROGID varchar(40) NOT NULL,
  MODIFYUSERID varchar(40) NOT NULL,
  MODIFYPROGID varchar(40) NOT NULL,
  CREATETS datetime DEFAULT current_timestamp(),
  MODIFYTS datetime DEFAULT current_timestamp(),
  DB_LOCK_VERSION bigint(20) DEFAULT 0,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PRODUCT (
  PRODUCT_KEY varchar(40) NOT NULL,
  TOTAL_QUANTITY double NOT NULL,
  UNIT varchar(40) NOT NULL,
  TOTAL_QUANTITY_EMPTY varchar(40) NOT NULL,
  ID varchar(36) NOT NULL,
  CREATEUSERID varchar(40) NOT NULL,
  CREATEPROGID varchar(40) NOT NULL,
  MODIFYUSERID varchar(40) NOT NULL,
  MODIFYPROGID varchar(40) NOT NULL,
  CREATETS datetime DEFAULT current_timestamp(),
  MODIFYTS datetime DEFAULT current_timestamp(),
  DB_LOCK_VERSION bigint(20) DEFAULT 0,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PRODUCT_LINE (
  PRODUCT_LINE_KEY varchar(40) NOT NULL,
  PRODUCT_KEY varchar(40) NOT NULL,
  SHELF_KEY varchar(40) NOT NULL,
  QUANTITY double NOT NULL,
  LENGTH double NOT NULL,
  WIDTH double NOT NULL,
  HEIGHT double NOT NULL,
  ID varchar(36) NOT NULL,
  CREATEUSERID varchar(40) NOT NULL,
  CREATEPROGID varchar(40) NOT NULL,
  MODIFYUSERID varchar(40) NOT NULL,
  MODIFYPROGID varchar(40) NOT NULL,
  CREATETS datetime DEFAULT current_timestamp(),
  MODIFYTS datetime DEFAULT current_timestamp(),
  DB_LOCK_VERSION bigint(20) DEFAULT 0,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;